name: homewalkers_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  bloc: ^9.0.0
  cloud_firestore: ^4.8.3
  firebase_core: ^2.14.0
  # cloud_firestore: ^5.6.8
  country_codes: ^3.3.0
  country_picker: ^2.0.27
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  equatable: ^2.0.7
  # firebase_core: ^3.13.1
  firebase_messaging: ^14.8.0  #
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_local_notifications: ^17.1.0
  flutter_screenutil: ^5.9.3
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  http: ^1.4.0
  intl: ^0.20.2
  intl_phone_field: ^3.2.0
  meta: ^1.16.0
  path_provider: ^2.0.11
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  # hive_generator: ^2.0.1
  # build_runner: ^2.3.3
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
